# Generated by Django 4.2.7 on 2023-11-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shutterlinkApp', '0005_alter_photographerprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographerprofile',
            name='brief_description',
        ),
    ]
